/* Generated by tools/puzzle.js — do not edit by hand.

   Metadata only: this is what the home card and the archive list need in
   order to render, so it is deliberately readable. Answers, author's notes
   and puzzle data all live encoded inside the per-puzzle modules, which are
   only fetched on the day they unlock. */

export const MANIFEST = [
  {"n":1,"title":"Orders of Magnitude","blurb":"Five quantities. You will not know any of them. Guess anyway.","goal":"Minimise your total error — being within 2× counts as a hit","emoji":"🔭"},
  {"n":2,"title":"Cold Open","blurb":"A quote, letter-swapped. Every A is some other letter, consistently.","goal":"Crack it using as few revealed letters as possible","emoji":"🔐"},
  {"n":3,"title":"The Rule","blurb":"I'm thinking of a rule about number triples. 2, 4, 6 obeys it.","goal":"Name the rule — using as few test triples as you can","emoji":"🔬"},
  {"n":4,"title":"Deep Time","blurb":"Six moments in history. Put them in order, oldest first.","goal":"Get all six right in as few checks as possible","emoji":"⏳"},
  {"n":5,"title":"How Sure Are You?","blurb":"Ten claims. Say how likely each is to be true — and mean it.","goal":"Lowest Brier score wins. Confidence is only a virtue when it's earned","emoji":"🎚️"},
  {"n":6,"title":"Give or Take","blurb":"Eight quantities. Don't guess the number — bracket it.","goal":"Catch the answer inside your range 7 times out of 8 — narrow ranges break ties","emoji":"📏"},
  {"n":7,"title":"The Odd Coin","blurb":"Twelve coins. One is fake — heavier or lighter, I won't tell you which. You have a balance scale.","goal":"Find the fake, and which way it's off, in as few weighings as possible — three is enough, done right","emoji":"🪙"},
  {"n":8,"title":"No Backsies","blurb":"You're selling. Offers arrive one at a time. Take one, or let it go — forever.","goal":"Come away with the best offer you can, over three rounds — hindsight will be watching","emoji":"🏷️"},
  {"n":9,"title":"Eyeball It","blurb":"Six scatterplots. How tight is the relationship? Trust your eye — then calibrate it.","goal":"Pin each correlation within 0.1 — smallest total error wins","emoji":"📉"},
  {"n":10,"title":"The Base Rate","blurb":"Five scenarios. Each gives you a number, then some evidence. What now?","goal":"Estimate the probability after the evidence — closest to the true figure wins","emoji":"🩺"},
  {"n":11,"title":"Second Opinion","blurb":"Ten more claims. Same deal: say how likely each is, and mean it.","goal":"Lowest Brier score wins. Confidence is only a virtue when it's earned","emoji":"⚖️"},
  {"n":12,"title":"Back of the Envelope","blurb":"Five more quantities, all of them reachable by multiplying things you know.","goal":"Minimise your total error — being within 2× counts as a hit","emoji":"✉️"},
  {"n":13,"title":"Room to Be Wrong","blurb":"Eight more quantities to fence in. One of them nobody can pin down at all.","goal":"Set 90% ranges. Catching seven of eight is the target, and narrower is better","emoji":"🎯"},
  {"n":14,"title":"Fooling Yourself","blurb":"One more swapped-letter quote. This one is the thesis of the whole project.","goal":"Crack it using as few revealed letters as possible","emoji":"🪞"},
  {"n":15,"title":"Further North Than You Think","blurb":"Six cities. Put them in order, northernmost at the top.","goal":"Get all six right in as few checks as possible","emoji":"🧭"},
  {"n":16,"title":"Sure About That?","blurb":"Ten claims. Say how likely each is to be true — and mean it.","goal":"Lowest Brier score wins. Confidence is only a virtue when it's earned","emoji":"🎛️"},
  {"n":17,"title":"Entertaining a Thought","blurb":"A quote, letter-swapped — and misattributed for two centuries.","goal":"Crack it using as few revealed letters as possible","emoji":"🗝️"},
  {"n":18,"title":"Nobody Knows That","blurb":"Eight quantities you have no business knowing. Fence them in anyway.","goal":"Catch the answer inside your range 7 times out of 8 — narrow ranges break ties","emoji":"🪤"},
  {"n":19,"title":"Twice As Obvious","blurb":"Another rule about number triples. This time 2, 4, 8 obeys it.","goal":"Name the rule — using as few test triples as you can","emoji":"🧫"},
  {"n":20,"title":"Trust Your Eye Again","blurb":"Six more scatterplots. How tight is each relationship, really?","goal":"Pin each correlation within 0.1 — smallest total error wins","emoji":"👁️"},
  {"n":21,"title":"Going, Going","blurb":"Three more auctions, one offer at a time. Take it or lose it.","goal":"Come away with the best offer you can, over three rounds — hindsight will be watching","emoji":"🔨"},
  {"n":22,"title":"The Camel","blurb":"A chess piece that doesn't exist. It moves like a knight with a longer stride — get it home.","goal":"Visit both marked squares, in order, in as few moves as you can — par is 9","emoji":"🐫"},
  {"n":23,"title":"The Grasshopper","blurb":"A piece that can't move at all unless something is in its way. Yesterday's camel is the only thing on the board.","goal":"Take the grasshopper to the gold square and back home, in as few moves as you can — par is 6","emoji":"🦗"},
  {"n":24,"title":"Mate in Two","blurb":"The camel and the grasshopper, together, against a cornered king. Black defends.","goal":"Force mate in two moves — Black will play the best defence every time","emoji":"♟️"},
  {"n":25,"title":"Everyone Lies","blurb":"Six islanders. Every truth-teller's statements are all true; every liar's are all false. Work out who's who.","goal":"Label all six correctly — confessions and wrong submissions both cost you","emoji":"🕊️"},
  {"n":26,"title":"Doublets","blurb":"Turn one word into another, one letter at a time — every stop has to be real.","goal":"Reach the target word in as few one-letter changes as possible; par is the true shortest route","emoji":"🪜"},
  {"n":27,"title":"Three Machines","blurb":"Three slot machines, forty pulls, one budget. Find the best one before you run out.","goal":"Two rounds of forty pulls each — scored on regret against the machine that actually paid best","emoji":"🎰"},
  {"n":28,"title":"Last Stone","blurb":"Three take-away games, one perfect opponent. Win all three, or start over.","goal":"Win each position without a restart — restarts against a perfect opponent are the score","emoji":"🪨"},
  {"n":29,"title":"Cracking the Safe","blurb":"Six symbols, four slots, no repeats. Each guess only tells you how many are locked in place and how many are loose — never which.","goal":"Crack the code in 4 guesses — that's the honest par, computed by actually solving it","emoji":"🔐"},
  {"n":30,"title":"Paint by Numbers","blurb":"A 10x10 grid, and only the row/column clues to go on. Fill the right cells and a picture appears.","goal":"Satisfy every row and column clue — wrong fills cost you, an unfinished grid doesn't count","emoji":"🖼️"},
  {"n":31,"title":"Odd One In","blurb":"Twelve cards. Find every trio where count, shape, shading and colour are each all the same or all different.","goal":"Find all five sets — the clock is running, wrong taps cost you","emoji":"👁️"},
  {"n":32,"title":"Lights Out","blurb":"Tap a light to toggle it and its neighbours. Turn every light off — in as few taps as possible.","goal":"Clear both rounds at the true minimum number of taps","emoji":"💡"},
  {"n":33,"title":"The Seam","blurb":"Five cryptic clues. Get the answer, then tap the words that are the straight definition — that seam is the whole trick.","goal":"Solve all five and correctly mark where the plain-English definition sits in each clue","emoji":"📖"},
  {"n":34,"title":"Jumping the Pegs","blurb":"A 15-hole triangle of pegs. Jump one peg over another into an empty hole to remove it. Get down to one.","goal":"Finish with as few pegs as possible — one is the perfect score","emoji":"⚫"},
  {"n":35,"title":"More or Less","blurb":"A 5x5 grid, no starting digits at all — just a scatter of < and > signs between cells. Fill 1-5 once per row and column.","goal":"Solve the whole grid — mistakes and hints both cost you","emoji":"🔢"},
  {"n":36,"title":"One Way Out","blurb":"A full car park, one exit, and every vehicle stuck with the direction it's facing. No reversing.","goal":"Free the marked vehicle from both lots in as few slides as you can — par is the true shortest escape","emoji":"🚗"},
  {"n":37,"title":"Island Hopping","blurb":"Fifteen islands, each wanting an exact number of bridges. Straight spans, no crossings, and everything has to end up connected.","goal":"Join every island to its exact number and leave the archipelago in one piece","emoji":"🌉"},
  {"n":38,"title":"Uneven Ground","blurb":"Sixteen words, four hidden categories — and not four apiece. You're told the sizes, not which is which.","goal":"Find all four categories — you get four wrong guesses and no more","emoji":"🪜"},
  {"n":39,"title":"Dead Weight","blurb":"Minesweeper where the numbers are weights, not counts: four of these eleven mines count double.","goal":"Clear all 53 safe squares without digging a mine — mistakes are the score","emoji":"🧨"},
  {"n":40,"title":"Signed For","blurb":"Push the crates onto the marks. A crate that reaches a mark is signed for — it becomes a wall.","goal":"Get every crate signed for in both rooms in as few steps as you can — par is the true shortest route","emoji":"🚚"},
  {"n":41,"title":"Nine Truths","blurb":"Five floors, five residents, five pets, five drinks. Ten clues — and one of them is a lie.","goal":"Fill the grid and name the false clue — both right, or neither","emoji":"🤥"},
  {"n":42,"title":"Common Knowledge","blurb":"Ivy was told the month. Otto was told the day. Neither says a number — and by the end, you know the date.","goal":"Strike out the impossible dates and lock in the right one, three times, without a wrong lock-in","emoji":"🗝️"},
  {"n":43,"title":"Two Fences","blurb":"Numbers count the sides a fence uses — but the answer is two separate closed loops, never one.","goal":"Close both grids into exactly two loops — hints and wrong closures are the score","emoji":"🚧"},
  {"n":44,"title":"Corner Pitch","blurb":"Every tree wants a tent diagonally from it. Tents may stand side by side — but never corner to corner.","goal":"Pitch both camps correctly — hints and wrong pitches are the score","emoji":"⛺"},
  {"n":45,"title":"Sonar","blurb":"A fleet is hidden in the sea. Four buoys, each reporting how many ship squares are near it — never which.","goal":"Find the whole fleet — hints and wrong fleets are the score","emoji":"🚢"}
];

export const BANK_SIZE = MANIFEST.length;
