import { el } from "./shared.js";
import { countSolutions, check, visible } from "./cave-rules.js";

export default { usesTimer: false, mount(root, puzzle, api) {
  const rounds = puzzle.data.rounds, solved = rounds.map((x) => { const r = countSolutions(x.spec, 2); if (r.count !== 1 || !r.exhausted) throw new Error(`cave: ${r.count} solutions`); return r.solutions[0]; });
  let ri = 0, bits = [], hints = 0, wrong = 0; const results = [], wrap = el("div"); root.appendChild(wrap);
  function render() { const s = rounds[ri].spec; wrap.innerHTML = ""; wrap.appendChild(el("p", "q-detail center", `Board ${ri + 1} of ${rounds.length} · outside ${bits.filter(Boolean).length}/${s.rows * s.cols}`)); const b = el("div"); b.style.display = "grid"; b.style.gridTemplateColumns = `repeat(${s.cols},1fr)`; b.style.maxWidth = "360px"; b.style.margin = "0 auto"; for (let r = 0; r < s.rows; r++) for (let c = 0; c < s.cols; c++) { const i = r * s.cols + c, clue = s.clues[r][c]; const q = el("button", null, clue == null ? (bits[i] ? "·" : "") : `${clue}`); q.style.aspectRatio = "1"; q.style.padding = "0"; q.style.background = bits[i] ? "rgba(255,255,255,.9)" : "rgba(255,255,255,.04)"; q.style.color = bits[i] ? "#111" : "inherit"; q.onclick = () => { bits[i] ^= 1; render(); if (check(s, bits).ok) done(); }; b.appendChild(q); } wrap.appendChild(b); const text = el("p", "q-detail center", "Tap cells to mark the connected OUTSIDE. A clue counts outside cells visible in its four directions."); wrap.appendChild(text); const bar = el("div", "stack"); bar.style.flexDirection = "row"; bar.style.justifyContent = "center"; const hint = el("button", "ghost compact", "Hint"); hint.onclick = () => { const i = bits.findIndex((x, j) => x !== solved[ri][j]); if (i >= 0) { bits[i] = solved[ri][i]; hints++; render(); } }; const clear = el("button", "ghost compact", "Clear"); clear.onclick = () => { bits.fill(0); render(); }; bar.append(hint, clear); wrap.appendChild(bar); }
  function done() { const s = rounds[ri].spec; if (!check(s, bits).ok) { wrong++; return; } results.push({ hints }); if (++ri < rounds.length) { bits = new Array(rounds[ri].spec.rows * rounds[ri].spec.cols).fill(0); hints = 0; render(); } else { const h = results.reduce((a, x) => a + x.hints, 0), clean = !h && !wrong; root.innerHTML = ""; api.finish({ headline: clean ? "The shore, no hints" : `The shore · ${h} hints`, squares: results.map((x) => x.hints ? "◻️" : "🌊").join(""), stats: [["Boards", `${rounds.length}/${rounds.length}`], ["Hints", String(h)], ["Wrong boards", String(wrong)]], perfect: clean, extra: [clean ? "🌊 unaided" : `💡 ${h} hints`], notes: solved.map((x, i) => `Board ${i + 1} — the unique outside region contains ${x.filter(Boolean).length} cells.`).concat("The clues count what lies outside the cave, so reading outward is the useful habit: an inside cell stops a sightline, while a long open ray contributes one cell at a time. Requiring both sides of the shore to stay connected and the boundary to be one closed loop prevents a collection of local islands from passing. The solver checks those global conditions after every candidate and exhausts the search after the second answer.") }); } }
  bits = new Array(rounds[0].spec.rows * rounds[0].spec.cols).fill(0); render();
} };
