/* Looking Out — a Cave/Corral-style binary grid. Outside cells are one
   connected border-reaching region, inside cells are one connected region, and
   the interface is a single closed loop. A clue counts contiguous outside
   cells visible in its four directions, stopping at the first inside cell. */
const O = [[-1, 0], [1, 0], [0, -1], [0, 1]];
function inside(spec, r, c) { return r >= 0 && c >= 0 && r < spec.rows && c < spec.cols; }
export function visible(spec, bits, r, c) { let n = 0; for (const [dr, dc] of O) { let rr = r + dr, cc = c + dc; while (inside(spec, rr, cc) && bits[rr * spec.cols + cc] === 1) { n++; rr += dr; cc += dc; } } return n; }
function connected(spec, bits, want) { const all = []; for (let r = 0; r < spec.rows; r++) for (let c = 0; c < spec.cols; c++) if (bits[r * spec.cols + c] === want) all.push(r * spec.cols + c); if (!all.length) return false; const seen = new Set([all[0]]), q = [all[0]]; while (q.length) { const k = q.pop(), r = Math.floor(k / spec.cols), c = k % spec.cols; for (const [dr, dc] of O) { const rr = r + dr, cc = c + dc, j = rr * spec.cols + cc; if (inside(spec, rr, cc) && bits[j] === want && !seen.has(j)) { seen.add(j); q.push(j); } } } return seen.size === all.length; }
export function loopCount(spec, bits) { const adj = new Map(); const add = (a, b) => { if (!adj.has(a)) adj.set(a, []); if (!adj.has(b)) adj.set(b, []); adj.get(a).push(b); adj.get(b).push(a); }; for (let r = 0; r < spec.rows; r++) for (let c = 0; c < spec.cols; c++) { if (r + 1 < spec.rows && bits[r * spec.cols + c] !== bits[(r + 1) * spec.cols + c]) add(`${r + 1},${c}`, `${r + 1},${c + 1}`); if (c + 1 < spec.cols && bits[r * spec.cols + c] !== bits[r * spec.cols + c + 1]) add(`${r},${c + 1}`, `${r + 1},${c + 1}`); } let loops = 0; const seen = new Set(); for (const [s] of adj) { if (seen.has(s)) continue; const q = [s]; seen.add(s); let v = 0, e = 0, ok = true; while (q.length) { const x = q.pop(); v++; const a = adj.get(x); e += a.length; if (a.length !== 2) ok = false; for (const y of a) if (!seen.has(y)) { seen.add(y); q.push(y); } } if (ok && e / 2 === v) loops++; } return loops; }
export function check(spec, bits) { if (!Array.isArray(bits) || bits.length !== spec.rows * spec.cols) return { ok: false, why: "choose every cell" }; if (!connected(spec, bits, 1) || !connected(spec, bits, 0)) return { ok: false, why: "inside and outside must each be one connected region" }; for (let r = 0; r < spec.rows; r++) for (let c = 0; c < spec.cols; c++) if (spec.clues[r][c] != null && visible(spec, bits, r, c) !== spec.clues[r][c]) return { ok: false, why: "a clue sees the wrong number of outside cells" }; return loopCount(spec, bits) === 1 ? { ok: true } : { ok: false, why: "the shore must be one closed loop" }; }
export function countSolutions(spec, limit = 2) { const total = spec.rows * spec.cols, bits = new Array(total).fill(0), solutions = []; let count = 0; function go(i) { if (count >= limit) return; if (i === total) { if (check(spec, bits).ok) { count++; solutions.push(bits.slice()); } return; } for (const b of [0, 1]) { bits[i] = b; go(i + 1); } } go(0); return { count, solutions, exhausted: count < limit }; }
export function par(spec) { const r = countSolutions(spec, 2); if (r.count !== 1 || !r.exhausted) throw new Error("cave: puzzle is not uniquely solved"); return spec.rows * spec.cols; }
