import { el } from "./shared.js";
import { countSolutions, check, moveKind } from "./knight-rules.js";
export default { usesTimer: false, mount(root, puzzle, api) {
  const rounds = puzzle.data.rounds, solved = rounds.map((x) => { const r = countSolutions(x.spec, 2); if (r.count !== 1 || !r.exhausted) throw new Error(`knight: ${r.count} solutions`); return r.solutions[0]; });
  let ri = 0, path = [], wrong = 0, hints = 0; const results = []; const wrap = el("div"); root.appendChild(wrap);
  function render() { const s = rounds[ri].spec, seen = new Map(path.map((p, i) => [p[0] * s.cols + p[1], i + 1])); wrap.innerHTML = ""; wrap.appendChild(el("p", "q-detail center", `Board ${ri + 1} of ${rounds.length} · ${path.length}/${s.rows * s.cols} visited · ${path.slice(1).filter((p, i) => moveKind(path[i], p) === "king").length}/2 king moves`)); const b = el("div"); b.style.display = "grid"; b.style.gridTemplateColumns = `repeat(${s.cols},1fr)`; b.style.maxWidth = "360px"; b.style.margin = "0 auto"; for (let r = 0; r < s.rows; r++) for (let c = 0; c < s.cols; c++) { const n = seen.get(r * s.cols + c), start = r === s.start[0] && c === s.start[1], end = r === s.end[0] && c === s.end[1], checkpoint = s.checkpoints?.some((x) => x.cell[0] === r && x.cell[1] === c); const q = el("button", null, n ? String(n) : start ? "S" : end ? "E" : checkpoint ? "◆" : ""); q.style.aspectRatio = "1"; q.style.padding = "0"; q.style.background = n ? "rgba(255,255,255,.9)" : start ? "rgba(244,197,66,.75)" : end ? "rgba(105,180,220,.45)" : "rgba(255,255,255,.06)"; q.style.color = n ? "#111" : "inherit"; if (checkpoint) q.style.outline = "2px solid #e5a84b"; q.onclick = () => tap(r, c); b.appendChild(q); } wrap.appendChild(b); const bar = el("div", "stack"); bar.style.flexDirection = "row"; bar.style.justifyContent = "center"; const undo = el("button", "ghost compact", "Undo"); undo.onclick = () => { if (path.length > 1) { path.pop(); render(); } }; const clear = el("button", "ghost compact", "Clear"); clear.onclick = () => { path = []; render(); }; const hint = el("button", "ghost compact", "Hint"); hint.onclick = () => { const target = solved[ri][path.length]; if (target) { path.push([...target]); hints++; render(); if (path.length === s.rows * s.cols) done(); } }; bar.append(undo, clear, hint); wrap.appendChild(bar); }
  function tap(r, c) { const s = rounds[ri].spec, k = r * s.cols + c; if (!path.length) { if (r === s.start[0] && c === s.start[1]) path.push([r, c]); else { wrong++; } render(); return; } if (path.some(([a, b]) => a === r && b === c)) return; if (!moveKind(path[path.length - 1], [r, c])) { wrong++; render(); return; } path.push([r, c]); render(); if (path.length === s.rows * s.cols) done(); }
  function done() { const s = rounds[ri].spec, r = check(s, path); if (!r.ok) { wrong++; path = []; render(); return; } results.push({ hints }); if (ri + 1 < rounds.length) { ri++; path = []; hints = 0; render(); } else { const h = results.reduce((a, x) => a + x.hints, 0), clean = !h && !wrong; root.innerHTML = ""; api.finish({ headline: clean ? "Every square, two short steps" : `Every square · ${h} hints`, squares: results.map((x) => x.hints ? "◻️" : "♞").join(""), stats: [["Boards", `${rounds.length}/${rounds.length}`], ["Hints", String(h)], ["Wrong moves", String(wrong)]], perfect: clean, extra: [clean ? "🎯 exact tour" : `💡 ${h} hints`], notes: solved.map((p, i) => `Board ${i + 1} — the unique tour has ${p.length - 1} moves and exactly two king steps.`).concat("The board asks for a complete tour, so every ordinary knight instinct still matters, but two consecutive squares may be joined by a king move. Those short steps are scarce resources: spend one too early and the endpoint can become unreachable, while saving both for a forced corner can be the only way through. The solver enumerates Hamiltonian paths, tracks king moves separately, stops after two candidates, and proves the authored endpoint pair has exactly one legal tour.") }); } }
  render();
} };
