/* Shakashaka variant: a clue counts triangles in all eight surrounding
   squares, including diagonals, instead of only the four orthogonal ones. */
const N8=[[-1,-1],[-1,0],[-1,1],[0,-1],[0,1],[1,-1],[1,0],[1,1]];
export function makeSpec(rows,cols,clues){return{rows,cols,clues};}
function inside(s,r,c){return r>=0&&c>=0&&r<s.rows&&c<s.cols;}
function rectangular(s,tri){const white=new Set();for(let r=0;r<s.rows;r++)for(let c=0;c<s.cols;c++)if(!tri.has(r*s.cols+c))white.add(r*s.cols+c);const seen=new Set();for(const start of white){if(seen.has(start))continue;const q=[start];seen.add(start);const comp=[];while(q.length){const i=q.pop(),r=Math.floor(i/s.cols),c=i%s.cols;comp.push([r,c]);for(const [dr,dc] of [[-1,0],[1,0],[0,-1],[0,1]]){const rr=r+dr,cc=c+dc,j=rr*s.cols+cc;if(inside(s,rr,cc)&&white.has(j)&&!seen.has(j)){seen.add(j);q.push(j);}}}const rs=comp.map(x=>x[0]),cs=comp.map(x=>x[1]);const minr=Math.min(...rs),maxr=Math.max(...rs),minc=Math.min(...cs),maxc=Math.max(...cs);if((maxr-minr+1)*(maxc-minc+1)!==comp.length)return false;}return true;}
export function check(s,triangles){const tri=new Set(triangles.map(([r,c])=>r*s.cols+c));for(const [k,v] of Object.entries(s.clues)){const [r,c]=k.split(",").map(Number);if(!inside(s,r,c))return{ok:false,why:"bad clue"};let n=0;for(const[dr,dc]of N8){const rr=r+dr,cc=c+dc;if(inside(s,rr,cc)&&tri.has(rr*s.cols+cc))n++;}if(n!==v)return{ok:false,why:`clue at ${r+1},${c+1} sees ${n}, needs ${v}`};if(tri.has(r*s.cols+c))return{ok:false,why:"a clue cell cannot be a triangle"};}if(!rectangular(s,tri))return{ok:false,why:"white cells do not form rectangles"};return{ok:true};}
export function countSolutions(s,limit=2){const free=[];for(let r=0;r<s.rows;r++)for(let c=0;c<s.cols;c++)if(s.clues[`${r},${c}`]===undefined)free.push([r,c]);const sols=[];let found=0;function go(i,tri){if(found>=limit)return;if(i===free.length){if(check(s,tri).ok){found++;sols.push(tri.slice());}return;}go(i+1,tri);tri.push(free[i]);go(i+1,tri);tri.pop();}go(0,[]);return{count:found,solutions:sols,exhausted:true};}
export function par(s){const r=countSolutions(s,2);if(r.count!==1)throw new Error("shakashaka: puzzle is not unique");return r.solutions[0].length;}
