import { el } from "./shared.js";
import { countSolutions, placementsFor, check } from "./statue-rules.js";

export default { usesTimer: false, mount(root, puzzle, api) {
  const rounds = puzzle.data.rounds, solved = rounds.map((x) => { const r = countSolutions(x.spec, 2); if (r.count !== 1 || !r.exhausted) throw new Error(`statue: ${r.count} solutions`); return r.solutions[0]; });
  let ri = 0, picked = [], hints = 0, wrong = 0; const results = [], wrap = el("div"); root.appendChild(wrap);
  function render() { const s = rounds[ri].spec, chosen = picked.map((p, i) => p ? { i, cells: p } : null).filter(Boolean), board = new Map(); for (const { i, cells } of chosen) for (const [r, c] of cells) board.set(`${r},${c}`, i); wrap.innerHTML = ""; wrap.appendChild(el("p", "q-detail center", `Park ${ri + 1} of ${rounds.length} · ${chosen.length}/${s.pieces.length} statues placed`)); const g = el("div"); g.style.display = "grid"; g.style.gridTemplateColumns = `repeat(${s.cols},1fr)`; g.style.maxWidth = "360px"; g.style.margin = "0 auto"; for (let r = 0; r < s.rows; r++) for (let c = 0; c < s.cols; c++) { const q = el("div", null, board.has(`${r},${c}`) ? String(board.get(`${r},${c}`) + 1) : "·"); q.style.aspectRatio = "1"; q.style.display = "grid"; q.style.placeItems = "center"; q.style.border = "1px solid rgba(255,255,255,.2)"; q.style.background = board.has(`${r},${c}`) ? "rgba(255,255,255,.8)" : "rgba(255,255,255,.04)"; q.style.color = board.has(`${r},${c}`) ? "#111" : "inherit"; g.appendChild(q); } wrap.appendChild(g); for (let i = 0; i < s.pieces.length; i++) { const row = el("div", "stack"); row.style.flexDirection = "row"; row.style.flexWrap = "wrap"; row.style.gap = "4px"; row.appendChild(el("span", "q-detail", `${s.pieces[i].id}:`)); placementsFor(s, i).forEach((p, j) => { const k = el("button", "ghost compact", `${p.anchor[0] + 1},${p.anchor[1] + 1}`); k.disabled = chosen.some((x) => x.i !== i && x.cells.some(([r, c]) => p.cells.some(([rr, cc]) => r === rr && c === cc))); k.onclick = () => { picked[i] = p.cells; render(); if (picked.filter(Boolean).length === s.pieces.length) done(); }; row.appendChild(k); }); wrap.appendChild(row); } const bar = el("div", "stack"); bar.style.flexDirection = "row"; bar.style.justifyContent = "center"; const hint = el("button", "ghost compact", "Hint"); hint.onclick = () => { const i = picked.findIndex((x, j) => !x || JSON.stringify(x) !== JSON.stringify(solved[ri][j])); if (i >= 0) { picked[i] = solved[ri][i]; hints++; render(); if (picked.filter(Boolean).length === s.pieces.length) done(); } }; const clear = el("button", "ghost compact", "Clear"); clear.onclick = () => { picked = []; render(); }; bar.append(hint, clear); wrap.appendChild(bar); }
  function done() { const s = rounds[ri].spec, r = check(s, picked); if (!r.ok) { wrong++; return; } results.push({ hints }); if (++ri < rounds.length) { picked = []; hints = 0; render(); } else { const h = results.reduce((a, x) => a + x.hints, 0), clean = !h && !wrong; root.innerHTML = ""; api.finish({ headline: clean ? "Park filled, no hints" : `Park filled · ${h} hints`, squares: results.map((x) => x.hints ? "◻️" : "🗿").join(""), stats: [["Parks", `${rounds.length}/${rounds.length}`], ["Hints", String(h)], ["Wrong parks", String(wrong)]], perfect: clean, extra: [clean ? "🗿 exact placement" : `💡 ${h} hints`], notes: solved.map((x, i) => `Park ${i + 1} — ${x.length} fixed statues tile every open square.`).concat("The fixed silhouettes make each translation a deliberate commitment: a statue can look perfect in isolation and still leave an impossible notch for its neighbour. The engine lists every legal anchor while keeping the piece orientation immutable, then checks that every square is covered exactly once. Its authoring search is the same exact-cover search used at mount, so the one packed tiling is proved rather than assumed.") }); } }
  picked = []; render();
} };
