#!/usr/bin/env node
/* ============================================================================
   PUZZLE CLI — authoring tool. Never shipped to the browser.

     node tools/puzzle.js unpack <n>   packed module  -> tools/content/00n.js
     node tools/puzzle.js pack <n>     tools/content/00n.js -> packed module
     node tools/puzzle.js pack-all     repack everything in tools/content
     node tools/puzzle.js verify       decode every puzzle and check its shape
     node tools/puzzle.js new <n>      scaffold a new content file

   Content lives readable in tools/content/ (gitignored) while you work on it,
   and only the encoded module gets committed. Round-trip freely: unpack, edit,
   pack. `verify` is the thing to run before committing.
   ========================================================================== */

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import { encode, decode } from "../codec.js";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const CONTENT = path.join(ROOT, "tools", "content");
const PUZZLES = path.join(ROOT, "puzzles");

const pad = (n) => String(n).padStart(3, "0");
const modPath = (n) => path.join(PUZZLES, `${pad(n)}.js`);
const srcPath = (n) => path.join(CONTENT, `${pad(n)}.js`);

/* Fields the manifest carries in the clear. Everything else is spoiler
   material and goes into the blob. */
const MANIFEST_FIELDS = ["n", "title", "blurb", "goal", "emoji"];

function readManifest() {
  const f = path.join(PUZZLES, "index.js");
  if (!fs.existsSync(f)) return [];
  const m = fs.readFileSync(f, "utf8").match(/export const MANIFEST = (\[[\s\S]*?\]);/);
  return m ? JSON.parse(m[1]) : [];
}

function writeManifest(entries) {
  entries.sort((a, b) => a.n - b.n);
  const body = entries.map((e) =>
    "  " + JSON.stringify(e, MANIFEST_FIELDS)).join(",\n");
  fs.writeFileSync(path.join(PUZZLES, "index.js"),
`/* Generated by tools/puzzle.js — do not edit by hand.

   Metadata only: this is what the home card and the archive list need in
   order to render, so it is deliberately readable. Answers, author's notes
   and puzzle data all live encoded inside the per-puzzle modules, which are
   only fetched on the day they unlock. */

export const MANIFEST = [
${body}
];

export const BANK_SIZE = MANIFEST.length;
`);
}

async function loadContent(n) {
  const mod = await import(pathToFileURL(srcPath(n)).href + `?t=${Date.now()}`);
  return mod.default;
}

/* Functions become "fn:..." strings on the way through JSON; mirror that when
   comparing so the round-trip check is apples to apples. */
function revivedShape(v) {
  if (typeof v === "string" && v.startsWith("fn:")) {
    return new Function(`return (${v.slice(3)})`)();
  }
  if (Array.isArray(v)) return v.map(revivedShape);
  if (v && typeof v === "object") {
    const o = {};
    for (const [k, val] of Object.entries(v)) o[k] = revivedShape(val);
    return o;
  }
  return v;
}

async function pack(n) {
  const c = await loadContent(n);
  for (const f of ["type", "title", "blurb", "goal", "emoji", "note", "data"]) {
    if (c[f] == null) throw new Error(`puzzle ${n}: missing "${f}"`);
  }
  const payload = { type: c.type, note: c.note, data: c.data };
  if (c.help) payload.help = c.help;   // the ? panel, spoiler-free but still hidden until unlock
  const blob = encode(payload, n);

  // Sanity: it must survive a round trip before we write anything.
  const back = decode(blob, n);
  if (String(JSON.stringify(back.data)) !== String(JSON.stringify(revivedShape(c.data)))) {
    throw new Error(`puzzle ${n}: round trip changed the data`);
  }

  fs.writeFileSync(modPath(n),
`/* Puzzle #${n} — "${c.title}"
   Encoded on purpose; see codec.js. To edit:
     node tools/puzzle.js unpack ${n} && node tools/puzzle.js pack ${n} */

export const blob = "${blob}";
`);

  const man = readManifest().filter((e) => e.n !== n);
  man.push({ n, title: c.title, blurb: c.blurb, goal: c.goal, emoji: c.emoji });
  writeManifest(man);
  console.log(`packed #${n} "${c.title}" (${blob.length}b blob)`);
}

function unpack(n) {
  const src = fs.readFileSync(modPath(n), "utf8");
  const blob = src.match(/export const blob = "([^"]+)"/)[1];
  const p = decode(blob, n);
  const meta = readManifest().find((e) => e.n === n) || {};
  fs.mkdirSync(CONTENT, { recursive: true });
  /* `help` is optional in the payload but it is still content: leaving it out
     here meant an unpack/pack round trip silently deleted a puzzle's ? panel. */
  const out = {
    type: p.type, title: meta.title, blurb: meta.blurb,
    goal: meta.goal, emoji: meta.emoji, note: p.note,
  };
  if (p.help) out.help = p.help;
  out.data = p.data;

  fs.writeFileSync(srcPath(n),
`/* Puzzle #${n} working copy — edit here, then: node tools/puzzle.js pack ${n} */

export default ${JSON.stringify(out,
  (k, v) => (typeof v === "function" ? "fn:" + v.toString() : v), 2)};
`);
  console.log(`unpacked #${n} -> tools/content/${pad(n)}.js`);
}

async function verify() {
  const man = readManifest();
  let bad = 0;
  for (const e of man) {
    try {
      const src = fs.readFileSync(modPath(e.n), "utf8");
      const blob = src.match(/export const blob = "([^"]+)"/)[1];
      const p = decode(blob, e.n);
      if (!p.type || !p.data || !p.note) throw new Error("incomplete payload");
      const engine = path.join(ROOT, "engines", `${p.type}.js`);
      if (!fs.existsSync(engine)) throw new Error(`no engine "${p.type}.js"`);
      console.log(`  ✓ #${e.n} ${e.emoji} ${e.title} — ${p.type}`);
    } catch (err) {
      console.log(`  ✗ #${e.n} ${e.title}: ${err.message}`);
      bad++;
    }
  }
  console.log(bad ? `\n${bad} broken` : `\n${man.length} puzzles, all good`);
  if (bad) process.exit(1);
}

function scaffold(n) {
  fs.mkdirSync(CONTENT, { recursive: true });
  if (fs.existsSync(srcPath(n))) throw new Error(`${srcPath(n)} already exists`);
  fs.writeFileSync(srcPath(n),
`export default {
  type: "fermi",              // an engine in engines/ — or add a new one
  title: "",
  blurb: "",                  // one line for the home card
  goal: "",                   // how this puzzle is scored, in plain words
  emoji: "",
  note: "",                   // shown only after they finish
  data: {},
};
`);
  console.log(`scaffolded tools/content/${pad(n)}.js`);
}

const [cmd, arg] = process.argv.slice(2);
const n = Number(arg);
try {
  if (cmd === "pack") await pack(n);
  else if (cmd === "unpack") unpack(n);
  else if (cmd === "new") scaffold(n);
  else if (cmd === "verify") await verify();
  else if (cmd === "pack-all") {
    const files = fs.readdirSync(CONTENT).filter((f) => /^\d+\.js$/.test(f));
    for (const f of files.sort()) await pack(Number(f.replace(".js", "")));
  } else {
    console.log("usage: puzzle.js <pack|unpack|new|pack-all|verify> [n]");
    process.exit(1);
  }
} catch (e) {
  console.error("error:", e.message);
  process.exit(1);
}
